spring.application.name=ds-petit

spring.datasource.url=jdbc:mysql://localhost:3306/petit
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# NÃO recria tudo, apenas ajusta
spring.jpa.hibernate.ddl-auto=create

# Permite rodar import.sql
spring.datasource.initialization-mode=always

spring.jpa.show-sql=true

app.upload.dir=c:/uploads