spring.application.name=ds-petit

spring.profiles.active=${APP_PROFILE:dev}

spring.jpa.open-in-view=true

cors.origins=${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}

jwt.secret=h8u0LF4ASpPzo/MCQGORlprOowgyWHUGEVcY5u1tozA9Fp2rpWYzUhZEU1Zt+hkvcpqtPk7Rk+Hpq/ksXVJv+w==
jwt.expiration=3600000


# =========================================
# EMAIL (SPRING MAIL)
# =========================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=luizhenriquemc15@gmail.com
spring.mail.password=bmkjjnjzvkwgzclp

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true