spring.application.name=ds-petit

spring.profiles.active=${APP_PROFILE:prod}

server.port=${PORT}
server.address=0.0.0.0

spring.jpa.open-in-view=true

cors.origins=${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}

jwt.secret=SEU_SECRET
jwt.expiration=3600000